import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { HashRouter, Routes, Route, NavLink } from 'react-router-dom'
import { motion, useScroll, useSpring } from 'framer-motion'
import CountUp from 'react-countup'
import { ArrowRight, BadgeCheck, BarChart3, BriefcaseBusiness, ChevronRight, Code2, Cpu, Globe2, GraduationCap, Layers3, Menu, MessageCircle, Palette, Phone, Rocket, School, Search, ShieldCheck, ShoppingCart, Smartphone, Sparkles, Star, Store, X, Zap } from 'lucide-react'
import './styles.css'
import logo from './assets/logo.png'
import { products, services, pricing, portfolio, whatsapp } from './data/site'

const iconMap = { Websites: Globe2, Mobile: Smartphone, Software: Code2, Design: Layers3, Branding: Palette, Marketing: BarChart3, SEO: Search, Cloud: ShieldCheck, AI: Cpu, Payments: BadgeCheck, Education: School, Retail: Store, Lifestyle: Sparkles, Repair: Cpu, 'Sports Tech': BarChart3, Enterprise: BriefcaseBusiness, CRM: Zap }
const fade = { hidden: { opacity: 0, y: 24 }, show: { opacity: 1, y: 0, transition: { duration: .65, ease: 'easeOut' } } }
function Reveal({ children, className='' }) { return <motion.div className={className} variants={fade} initial="hidden" whileInView="show" viewport={{ once: true, margin: '-80px' }}>{children}</motion.div> }
function Header(){ const [open,setOpen]=useState(false); const nav=['Home','About','Services','Products','Pricing','Portfolio','Contact']; return <header className="site-header"><NavLink to="/" className="brand"><img src={logo}/><span>AFRIDEVELOPERS</span></NavLink><button className="menu-btn" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''}>{nav.map(n=><NavLink key={n} to={n==='Home'?'/':'/'+n.toLowerCase()} onClick={()=>setOpen(false)}>{n}</NavLink>)}<a className="whats" href={whatsapp}><MessageCircle size={18}/> WhatsApp</a></nav></header> }
function Hero(){ return <section className="hero"><div className="mesh"></div><motion.div className="hero-copy" initial={{opacity:0,y:35}} animate={{opacity:1,y:0}} transition={{duration:.8}}><p className="eyebrow"><Sparkles size={18}/> Premium digital solutions in Uganda</p><h1>We build websites, apps, brands and systems that make businesses look serious.</h1><p className="lead">AfriDevelopers creates modern digital products for companies, schools, shops, real estate brands, events, startups and growing African businesses.</p><div className="actions"><a href={whatsapp} className="btn primary"><MessageCircle/> Start on WhatsApp</a><NavLink to="/services" className="btn secondary">Explore Services <ArrowRight/></NavLink></div></motion.div><motion.div className="hero-panel" initial={{opacity:0,scale:.9,rotate:-2}} animate={{opacity:1,scale:1,rotate:0}} transition={{duration:.9,delay:.2}}><img src={logo}/><div className="panel-list"><span>Websites</span><span>Mobile Apps</span><span>Branding</span><span>Marketing</span><span>POS Systems</span><span>School Systems</span></div></motion.div></section> }
function Stats(){ return <section className="stats"><Reveal><strong><CountUp end={30} suffix="+" enableScrollSpy/></strong><span>Digital services</span></Reveal><Reveal><strong><CountUp end={12} suffix="+" enableScrollSpy/></strong><span>Software products</span></Reveal><Reveal><strong><CountUp end={99} suffix="%" enableScrollSpy/></strong><span>Responsive layouts</span></Reveal><Reveal><strong><CountUp end={24} suffix="/7" enableScrollSpy/></strong><span>Online visibility</span></Reveal></section> }
function ServicesBlock(){ return <section className="section"><Reveal><p className="eyebrow">What we do</p><h2>Services designed for growth</h2></Reveal><div className="grid cards">{services.map(([title,text,price,type])=>{const Icon=iconMap[type]||Code2;return <Reveal className="card service-card" key={title}><div className="icon"><Icon/></div><h3>{title}</h3><p>{text}</p><div className="card-foot"><b>{price}</b><a href={whatsapp}>Request <ChevronRight size={16}/></a></div></Reveal>})}</div></section> }
function ProductsBlock(){ return <section className="section dark"><Reveal><p className="eyebrow">Product suite</p><h2>AfriDevelopers software products</h2></Reveal><div className="grid products">{products.map(([name,desc,type])=>{const Icon=iconMap[type]||Rocket;return <Reveal className="product" key={name}><span className="tag">{type}</span><Icon className="prod-icon"/><h3>{name}</h3><p>{desc}</p><a href={whatsapp}>Request demo</a></Reveal>})}</div></section> }
function PricingBlock(){ return <section className="section"><Reveal><p className="eyebrow">Professional pricing</p><h2>Clear starting prices in UGX</h2></Reveal><Reveal className="price-box">{pricing.map(([name,cost])=><div className="price-row" key={name}><span><BadgeCheck size={18}/>{name}</span><b>{cost}</b></div>)}<a className="btn primary full" href={whatsapp}>Get a custom quotation on WhatsApp</a></Reveal></section> }
function PortfolioBlock(){ return <section className="section dark"><Reveal><p className="eyebrow">Portfolio style</p><h2>Premium layouts for modern brands</h2></Reveal><div className="grid portfolio">{portfolio.map((p,i)=><Reveal className="work" key={p}><div className="work-top"><span>0{i+1}</span><Star/></div><h3>{p}</h3><p>Built with clean sections, quality typography, smooth transitions, responsive structure and strong conversion calls-to-action.</p></Reveal>)}</div></section> }
function About(){ return <><section className="page-hero"><p className="eyebrow">About AfriDevelopers</p><h1>Technology, design and strategy for African businesses.</h1><p>We help businesses move from ordinary presentation to professional digital identity through websites, apps, systems, marketing and branding.</p></section><section className="split"><Reveal><h2>Our mission</h2><p>To build reliable digital tools that help businesses sell, manage, communicate and grow with confidence.</p></Reveal><Reveal className="glass"><h3>Why clients choose us</h3><ul><li>Modern UI with premium fonts</li><li>Mobile-first development</li><li>WhatsApp-focused lead generation</li><li>Clear packages and scalable products</li></ul></Reveal></section></> }
function Services(){ return <><section className="page-hero"><p className="eyebrow">Services</p><h1>Everything your business needs online.</h1><p>From logo to website, mobile app, marketing, SEO, hosting and custom software systems.</p></section><ServicesBlock/></> }
function Products(){ return <><section className="page-hero"><p className="eyebrow">Products</p><h1>Business software ready for African markets.</h1><p>AfriPay, AfriSchool, AfriPOS, Vibendo and more products designed to solve real business problems.</p></section><ProductsBlock/></> }
function Pricing(){ return <><section className="page-hero"><p className="eyebrow">Pricing</p><h1>Professional pricing that helps clients choose faster.</h1><p>These are starting prices. Final cost depends on project size, features, integrations and timeline.</p></section><PricingBlock/></> }
function Portfolio(){ return <><section className="page-hero"><p className="eyebrow">Portfolio</p><h1>Project categories AfriDevelopers can deliver.</h1><p>Use this page to present completed work, screenshots and client case studies as your portfolio grows.</p></section><PortfolioBlock/></> }
function Contact(){ return <><section className="page-hero"><p className="eyebrow">Contact</p><h1>Let’s build something professional.</h1><p>Talk to AfriDevelopers on WhatsApp for websites, apps, systems, branding and digital marketing.</p><a className="btn primary" href={whatsapp}><Phone/> Chat on WhatsApp</a></section><section className="contact-card"><h2>Project inquiry</h2><p>For fastest response, send your business name, service needed, budget range and deadline on WhatsApp.</p><a href={whatsapp} className="btn secondary"><MessageCircle/> Open WhatsApp</a></section></> }
function Home(){ return <><Hero/><Stats/><ServicesBlock/><ProductsBlock/><PricingBlock/><PortfolioBlock/><section className="cta"><Reveal><Rocket/><h2>Ready to upgrade your digital presence?</h2><p>Get a premium website, app, system, brand identity or marketing package for your business.</p><a href={whatsapp} className="btn primary"><MessageCircle/> Chat on WhatsApp</a></Reveal></section></> }
function App(){ const {scrollYProgress}=useScroll(); const scaleX=useSpring(scrollYProgress,{stiffness:120,damping:30}); useEffect(()=>window.scrollTo(0,0),[]); return <HashRouter><motion.div className="progress" style={{scaleX}}/><Header/><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/services" element={<Services/>}/><Route path="/products" element={<Products/>}/><Route path="/pricing" element={<Pricing/>}/><Route path="/portfolio" element={<Portfolio/>}/><Route path="/contact" element={<Contact/>}/></Routes><a className="float" href={whatsapp}>💬</a><footer><b>AFRIDEVELOPERS</b><span> © {new Date().getFullYear()} Websites • Apps • Branding • Marketing • Business Systems</span></footer></HashRouter> }

createRoot(document.getElementById('root')).render(<App />)
