import React,{useState,useEffect} from 'react';import{createRoot}from'react-dom/client';import{Menu,X,ArrowRight,Check,MessageCircle,Globe,Smartphone,Palette,BarChart3,Shield,Cloud,Brain,ShoppingCart,School,Wallet,MapPin,Phone,Mail,Star}from'lucide-react';import{services,products,pricing,portfolio,industries}from'./data';import'./styles.css';
const wa='https://wa.me/256767432176?text=Hello%20AfriDevelopers,%20I%20need%20a%20digital%20solution.';
function Nav(){const[open,setOpen]=useState(false);const links=['Home','Services','Products','Pricing','Portfolio','Contact'];return <><nav className="nav"><a href="#home" className="brand"><img src="/assets/logo.png"/><span>AfriDevelopers</span></a><div className="links">{links.map(l=><a key={l} href={'#'+l.toLowerCase()}>{l}</a>)}<a className="btn small" href={wa}>WhatsApp</a></div><button className="hamb" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></nav>{open&&<div className="mobile">{links.map(l=><a onClick={()=>setOpen(false)} key={l} href={'#'+l.toLowerCase()}>{l}</a>)}<a className="btn" href={wa}>Chat on WhatsApp</a></div>}</>}
function Reveal({children,cls=''}){return <div className={'reveal '+cls}>{children}</div>}
function Hero(){return <section id="home" className="hero"><div className="orb o1"></div><div className="orb o2"></div><div className="heroText"><p className="eyebrow">Premium Digital Solutions Company in Uganda</p><h1>We build websites, apps, brands and business systems that help African companies grow.</h1><p className="lead">AfriDevelopers delivers modern software, digital marketing, business automation, AI, cloud, branding and product innovation for startups, SMEs and enterprises.</p><div className="heroBtns"><a className="btn" href={wa}><MessageCircle/> Start on WhatsApp</a><a className="btn ghost" href="#services">Explore Services <ArrowRight/></a></div><div className="stats"><b>50+</b><span>Solutions</span><b>12+</b><span>Products</span><b>24/7</b><span>Support mindset</span></div></div><div className="heroCard"><img src="/assets/logo.png"/><h3>AfriDevelopers Digital Suite</h3><p>Web • Mobile • POS • School • Payments • Branding • Marketing • AI</p><div className="miniGrid">{['React','Vite','Cloud','SEO','UI/UX','Mobile'].map(x=><span>{x}</span>)}</div></div></section>}
function Services(){const icons=[Globe,Smartphone,BarChart3,Palette,ShoppingCart,Brain,Cloud,Shield];return <section id="services" className="section"><Reveal><p className="eyebrow">What we do</p><h2>Complete AfriDevelopers Services</h2><p className="sub">Every service is presented professionally with clear value, modern design, scalable code and business-focused delivery.</p></Reveal><div className="grid cards">{services.map((s,i)=>{const I=icons[i%icons.length];return <article className="card" key={s[0]}><I className="icon"/><h3>{s[0]}</h3><p>{s[1]}</p><b>{s[2]}</b><a href={wa}>Discuss on WhatsApp <ArrowRight size={16}/></a></article>})}</div></section>}
function Products(){const icons=[Wallet,School,ShoppingCart,MapPin,BarChart3,Shield,Globe,Smartphone];return <section id="products" className="section alt"><p className="eyebrow">AfriDevelopers Products</p><h2>Software products built for African businesses</h2><div className="grid productGrid">{products.map((p,i)=>{const I=icons[i%icons.length];return <div className="product" key={p[0]}><div><I/><h3>{p[0]}</h3></div><p>{p[1]}</p><ul><li><Check/> Dashboard ready</li><li><Check/> Scalable modules</li><li><Check/> Demo request available</li></ul><a className="btn small" href={wa}>Request Demo</a></div>})}</div></section>}
function Pricing(){return <section id="pricing" className="section"><p className="eyebrow">Transparent Pricing</p><h2>Professional pricing for digital solutions</h2><div className="grid priceGrid">{pricing.map(p=><div className="price" key={p[0]}><h3>{p[0]}</h3><p>{p[1]}</p><strong>{p[2]}</strong>{p[3].map(f=><span><Check size={17}/>{f}</span>)}<a className="btn" href={wa}>Order on WhatsApp</a></div>)}</div></section>}
function Portfolio(){return <section id="portfolio" className="section alt"><p className="eyebrow">Portfolio & Industries</p><h2>Designed for real business needs</h2><div className="showcase">{portfolio.map(x=><div className="shot"><div className="browser"><i></i><i></i><i></i></div><h3>{x}</h3><p>Strategy, design, development, launch support and optimization.</p></div>)}</div><h2 className="mt">Industries we serve</h2><div className="chips">{industries.map(x=><span>{x}</span>)}</div></section>}
function About(){return <section className="section about"><div><p className="eyebrow">Why choose us</p><h2>Africa-focused technology with premium execution</h2><p>AfriDevelopers combines software engineering, digital strategy, creative branding and business understanding to deliver practical solutions for Uganda and beyond. We build systems that are clean, fast, responsive, scalable and easy for clients to use.</p><div className="ticks">{['Business-first planning','Premium UI and animations','Mobile responsive design','SEO and performance','WhatsApp conversion flows','Long-term support'].map(x=><span><Check/>{x}</span>)}</div></div><div className="glass"><h3>Development process</h3>{['Discovery','Design','Development','Testing','Launch','Support'].map((x,i)=><p><b>0{i+1}</b> {x}</p>)}</div></section>}
function Contact(){return <section id="contact" className="section contact"><div><p className="eyebrow">Start a project</p><h2>Let’s build your next digital product</h2><p>Contact AfriDevelopers for websites, apps, POS, school systems, digital marketing, branding, AI and cloud solutions.</p><p><Phone/> +256 767 432176</p><p><Mail/> info@afridevelopers.com</p><p><MapPin/> Seeta–Namilyango Road, Uganda</p></div><form onSubmit={e=>{e.preventDefault();location.href=wa}}><input placeholder="Your name"/><input placeholder="Phone or email"/><select><option>Website Development</option><option>Mobile App</option><option>AfriPOS</option><option>AfriSchool</option><option>Branding</option><option>Digital Marketing</option></select><textarea placeholder="Tell us about your project"></textarea><button className="btn">Send via WhatsApp</button></form></section>}
function Footer(){return <footer><div><img src="/assets/logo.png"/><b>AfriDevelopers</b><p>Building Africa’s next generation of digital products.</p></div><div><b>Services</b><a>Websites</a><a>Apps</a><a>Branding</a><a>Marketing</a></div><div><b>Products</b><a>AfriPay</a><a>AfriSchool</a><a>AfriPOS</a><a>Vibendo</a></div><div><b>Contact</b><a href={wa}>WhatsApp</a><a>info@afridevelopers.com</a></div></footer>}
function App(){useEffect(()=>{const els=document.querySelectorAll('.reveal,.card,.product,.price,.shot');const io=new IntersectionObserver(e=>e.forEach(x=>x.isIntersecting&&x.target.classList.add('show')),{threshold:.1});els.forEach(el=>io.observe(el));return()=>io.disconnect()},[]);return <><Nav/><Hero/><Services/><Products/><Pricing/><Portfolio/><About/><Contact/><Footer/><a className="float" href={wa}><MessageCircle/></a></>}
createRoot(document.getElementById('root')).render(<App/>);
